FIELD_SYNONYMS = {
    "product_name": ["article", "product", "item", "produit", "designation", "libelle", "art", "nom produit"],
    "quantity": ["qte", "qty", "quantite", "count", "nombre", "qte_vendue", "units", "unites", "quantityordered"],
    "revenue": ["montant", "montant ht", "montant total", "total", "amount", "prix total",
                "chiffre affaire", "ca", "mt_ht", "total revenue", "sales amount", "sales"],
    "sale_date": ["date", "date vente", "date de vente", "order date", "orderdate",
                  "transaction date", "dt", "date achat"],
    "unit_price": ["prix unitaire", "pu", "price per unit", "unit cost", "prix", "cout unitaire",
                   "priceeach", "price each"],
    "customer_name": ["client", "nom client", "customer", "buyer", "acheteur", "nom du client",
                       "customername", "customer name"],
    "customer_id": ["id client", "customer id", "ref client", "client id", "numero client", "cust_id",
                     "customerid"],
    "category": ["categorie", "cat", "product category", "type produit", "famille", "productline",
                 "product line"],
    "discount": ["remise", "reduction", "discount pct", "rabais", "promo"],
    "tax_amount": ["tva", "taxe", "vat", "tax", "montant tva"],
    "payment_method": ["mode paiement", "payment type", "moyen de paiement", "paiement"],
    "store_location": ["magasin", "store", "location", "point de vente", "boutique", "succursale"],
    "salesperson": ["vendeur", "sales rep", "commercial", "employe", "agent"],
    "invoice_number": ["facture", "invoice", "numero facture", "num facture", "ref facture",
                       "ordernumber", "order number", "order id", "orderid"],
    "currency": ["devise", "monnaie", "curr"],

    "order_status": ["status", "statut", "order status", "etat commande", "etat"],
    "order_line_number": ["orderlinenumber", "order line number", "line number", "ligne commande",
                          "numero ligne", "line no"],
    "product_code": ["productcode", "product code", "code produit", "ref produit", "sku",
                      "reference produit"],
    "msrp": ["msrp", "manufacturer suggested retail price", "prix conseille", "prix catalogue"],
    "deal_size": ["dealsize", "deal size", "taille commande", "order size"],

    "sale_year": ["year_id", "year", "annee", "annee vente"],
    "sale_quarter": ["qtr_id", "quarter", "trimestre", "qtr"],
    "sale_month": ["month_id", "month", "mois", "mois vente"],

    "phone": ["phone", "telephone", "tel", "numero telephone", "num tel", "phone number"],
    "address_line1": ["addressline1", "address line 1", "adresse", "adresse 1", "address 1"],
    "address_line2": ["addressline2", "address line 2", "adresse 2", "address 2", "complement adresse"],
    "city": ["city", "ville", "town"],
    "state": ["state", "region", "etat", "province"],
    "postal_code": ["postalcode", "postal code", "code postal", "zip", "zip code", "zipcode"],
    "country": ["country", "pays"],
    "territory": ["territory", "territoire", "zone", "secteur"],

    "contact_first_name": ["contactfirstname", "contact first name", "prenom contact", "first name",
                            "prenom"],
    "contact_last_name": ["contactlastname", "contact last name", "nom contact", "last name",
                           "nom"],
}